// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv5u1TIJDusFtY7Bef_X_TgsaRdV_2qS0',
    appId: '1:421970184365:web:2c1f855030a528c3cf1e24',
    messagingSenderId: '421970184365',
    projectId: 'tutor-zone-996b0',
    authDomain: 'tutor-zone-996b0.firebaseapp.com',
    storageBucket: 'tutor-zone-996b0.firebasestorage.app',
    measurementId: 'G-PQHYBNX0W1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7U3Ya6vg7C3QhxTsJdWTEFTaEZi0ztXY',
    appId: '1:421970184365:android:2371538b195d8ba4cf1e24',
    messagingSenderId: '421970184365',
    projectId: 'tutor-zone-996b0',
    storageBucket: 'tutor-zone-996b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASd5rrVeZ-eMjQdNNsitaR7MD4SA2AESY',
    appId: '1:421970184365:ios:71ef30cb913952dbcf1e24',
    messagingSenderId: '421970184365',
    projectId: 'tutor-zone-996b0',
    storageBucket: 'tutor-zone-996b0.firebasestorage.app',
    iosBundleId: 'com.example.tutorZone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASd5rrVeZ-eMjQdNNsitaR7MD4SA2AESY',
    appId: '1:421970184365:ios:71ef30cb913952dbcf1e24',
    messagingSenderId: '421970184365',
    projectId: 'tutor-zone-996b0',
    storageBucket: 'tutor-zone-996b0.firebasestorage.app',
    iosBundleId: 'com.example.tutorZone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv5u1TIJDusFtY7Bef_X_TgsaRdV_2qS0',
    appId: '1:421970184365:web:9a3fac61b4777d8bcf1e24',
    messagingSenderId: '421970184365',
    projectId: 'tutor-zone-996b0',
    authDomain: 'tutor-zone-996b0.firebaseapp.com',
    storageBucket: 'tutor-zone-996b0.firebasestorage.app',
    measurementId: 'G-RW3Z8B275K',
  );
}
