// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl6z91hJlPRI3dLe7kdV9lyQzDPe7e228',
    appId: '1:212802016089:web:4c3a2e9b6d67a3236f7248',
    messagingSenderId: '212802016089',
    projectId: 'tutor-zone-prod',
    authDomain: 'tutor-zone-prod.firebaseapp.com',
    storageBucket: 'tutor-zone-prod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO1QHN1gjMh14S9ciEMeztKFmu-n6J7B4',
    appId: '1:212802016089:android:cc8d37399d48e8846f7248',
    messagingSenderId: '212802016089',
    projectId: 'tutor-zone-prod',
    storageBucket: 'tutor-zone-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr4AJXp_9OPrhAM7l8hgNwCEVYAt3Prkk',
    appId: '1:212802016089:ios:a47a17f7d0b045206f7248',
    messagingSenderId: '212802016089',
    projectId: 'tutor-zone-prod',
    storageBucket: 'tutor-zone-prod.firebasestorage.app',
    iosBundleId: 'com.example.tutorZone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr4AJXp_9OPrhAM7l8hgNwCEVYAt3Prkk',
    appId: '1:212802016089:ios:a47a17f7d0b045206f7248',
    messagingSenderId: '212802016089',
    projectId: 'tutor-zone-prod',
    storageBucket: 'tutor-zone-prod.firebasestorage.app',
    iosBundleId: 'com.example.tutorZone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl6z91hJlPRI3dLe7kdV9lyQzDPe7e228',
    appId: '1:212802016089:web:4c3a2e9b6d67a3236f7248',
    messagingSenderId: '212802016089',
    projectId: 'tutor-zone-prod',
    authDomain: 'tutor-zone-prod.firebaseapp.com',
    storageBucket: 'tutor-zone-prod.firebasestorage.app',
  );
}
