// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv5u1TIJDusFtY7Bef_X_TgsaRdV_2qS0',
    appId: '1:421970184365:web:d09346aab0dd8ceacf1e24',
    messagingSenderId: '421970184365',
    projectId: 'tutor-zone-996b0',
    authDomain: 'tutor-zone-996b0.firebaseapp.com',
    storageBucket: 'tutor-zone-996b0.firebasestorage.app',
    measurementId: 'G-TSKZK40JVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7U3Ya6vg7C3QhxTsJdWTEFTaEZi0ztXY',
    appId: '1:421970184365:android:4f50a1da76063fbacf1e24',
    messagingSenderId: '421970184365',
    projectId: 'tutor-zone-996b0',
    storageBucket: 'tutor-zone-996b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASd5rrVeZ-eMjQdNNsitaR7MD4SA2AESY',
    appId: '1:421970184365:ios:d5ec60356ddbe769cf1e24',
    messagingSenderId: '421970184365',
    projectId: 'tutor-zone-996b0',
    storageBucket: 'tutor-zone-996b0.firebasestorage.app',
    iosBundleId: 'com.example.tutorZone.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASd5rrVeZ-eMjQdNNsitaR7MD4SA2AESY',
    appId: '1:421970184365:ios:d5ec60356ddbe769cf1e24',
    messagingSenderId: '421970184365',
    projectId: 'tutor-zone-996b0',
    storageBucket: 'tutor-zone-996b0.firebasestorage.app',
    iosBundleId: 'com.example.tutorZone.dev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv5u1TIJDusFtY7Bef_X_TgsaRdV_2qS0',
    appId: '1:421970184365:web:d09346aab0dd8ceacf1e24',
    messagingSenderId: '421970184365',
    projectId: 'tutor-zone-996b0',
    authDomain: 'tutor-zone-996b0.firebaseapp.com',
    storageBucket: 'tutor-zone-996b0.firebasestorage.app',
    measurementId: 'G-TSKZK40JVH',
  );
}
